<?php

namespace Adrianovcar\Asaas\Entity;

class PaymentStatus
{
    const PENDING = 'PENDING';
    const RECEIVED = 'RECEIVED';
    const CONFIRMED = 'CONFIRMED';
    const OVERDUE = 'OVERDUE';
    const REFUNDED = 'REFUNDED';
    const RECEIVED_IN_CASH = 'RECEIVED_IN_CASH';
    const REFUND_REQUESTED = 'REFUND_REQUESTED';
    const REFUND_IN_PROGRESS = 'REFUND_IN_PROGRESS';
    const CHARGEBACK_REQUESTED = 'CHARGEBACK_REQUESTED';
    const CHARGEBACK_DISPUTE = 'CHARGEBACK_DISPUTE';
    const AWAITING_CHARGEBACK_REVERSAL = 'AWAITING_CHARGEBACK_REVERSAL';
    const DUNNING_REQUESTED = 'DUNNING_REQUESTED';
    const DUNNING_RECEIVED = 'DUNNING_RECEIVED';
    const AWAITING_RISK_ANALYSIS = 'AWAITING_RISK_ANALYSIS';
}
